### ISSUE TITLE
issue with shooting and dragging the player

### ISSUE THREAD

**Issue by Jeffchiucp** [jorgeavelar98/Take-Me-Home#3]
User testing identified an issue with shooting and dragging the player.
Please resolved this issue @jorgeavelar98 , so the user can drag the player while shooting at the same time.

**Comment by jorgeavelar98** [comment]
In the process of fixing. Thanks!

**Comment by Jeffchiucp** [comment]
Beta User Testing!

**Comment by jorgeavelar98** [comment]
I have figured it out. The user can now shoot and drag without interference.
